//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocPASEntities : DbContext
    {
        public DocPASEntities()
            : base("name=DocPASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Sub24> Sub24 { get; set; }
        public virtual DbSet<Sub25> Sub25 { get; set; }
        public virtual DbSet<Sub26> Sub26 { get; set; }
        public virtual DbSet<Sub27> Sub27 { get; set; }
        public virtual DbSet<Sub28> Sub28 { get; set; }
        public virtual DbSet<Sub35> Sub35 { get; set; }
        public virtual DbSet<Sub36> Sub36 { get; set; }
        public virtual DbSet<Sub37> Sub37 { get; set; }
        public virtual DbSet<Sub38> Sub38 { get; set; }
        public virtual DbSet<Sub39> Sub39 { get; set; }
        public virtual DbSet<Sub40> Sub40 { get; set; }
        public virtual DbSet<Sub53> Sub53 { get; set; }
        public virtual DbSet<Sub54> Sub54 { get; set; }
        public virtual DbSet<Sub56> Sub56 { get; set; }
        public virtual DbSet<Sub57> Sub57 { get; set; }
        public virtual DbSet<Sub58> Sub58 { get; set; }
        public virtual DbSet<Sub59> Sub59 { get; set; }
        public virtual DbSet<Sub60> Sub60 { get; set; }
        public virtual DbSet<Report62> Report62 { get; set; }
        public virtual DbSet<Report63> Report63 { get; set; }
        public virtual DbSet<Report64> Report64 { get; set; }
        public virtual DbSet<Report17> Report17 { get; set; }
        public virtual DbSet<Report18> Report18 { get; set; }
        public virtual DbSet<Report23> Report23 { get; set; }
        public virtual DbSet<Report51> Report51 { get; set; }
        public virtual DbSet<Report52> Report52 { get; set; }
        public virtual DbSet<Report53> Report53 { get; set; }
        public virtual DbSet<Report54> Report54 { get; set; }
        public virtual DbSet<Report56> Report56 { get; set; }
        public virtual DbSet<Report58> Report58 { get; set; }
        public virtual DbSet<Report59> Report59 { get; set; }
        public virtual DbSet<Report41> Report41 { get; set; }
        public virtual DbSet<Report42> Report42 { get; set; }
        public virtual DbSet<Report43> Report43 { get; set; }
        public virtual DbSet<Report44> Report44 { get; set; }
        public virtual DbSet<Report45> Report45 { get; set; }
        public virtual DbSet<Report46> Report46 { get; set; }
        public virtual DbSet<Report47> Report47 { get; set; }
        public virtual DbSet<Report48> Report48 { get; set; }
        public virtual DbSet<Report49> Report49 { get; set; }
        public virtual DbSet<Report50> Report50 { get; set; }
        public virtual DbSet<DepartmentMapping> DepartmentMappings { get; set; }
        public virtual DbSet<DepartmentMasterReport> DepartmentMasterReports { get; set; }
        public virtual DbSet<SubMasterReport> SubMasterReports { get; set; }
        public virtual DbSet<Sub61> Sub61 { get; set; }
        public virtual DbSet<Subjects_MarksMapping> Subjects_MarksMapping { get; set; }
        public virtual DbSet<Departments_MarksMapping> Departments_MarksMapping { get; set; }
    }
}
