//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments_MarksMapping
    {
        public int Id { get; set; }
        public Nullable<int> DId { get; set; }
        public Nullable<int> Marks1 { get; set; }
        public Nullable<int> Marks2 { get; set; }
        public Nullable<int> Marks3 { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
