//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Report14
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }



        [Required(ErrorMessage = "कृपया कार्यालयातील वर्गीकरणानुसार अभिलेखामध्ये पाठविण्यास उपलब्ध असलेल्या प्रकरणांची संख्या आवश्यक आहे")]
        [DisplayName("कार्यालयातील वर्गीकरणानुसार अभिलेखामध्ये पाठविण्यास उपलब्ध असलेल्या प्रकरणे")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Available_Applications { get; set; }



        [Required(ErrorMessage = "कृपया चालु महिना अखेर उद्दीष्टे संख्या आवश्यक आहे")]
        [DisplayName("चालु महिना अखेर उद्दीष्टे")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Current_Month_Aim { get; set; }




        [Required(ErrorMessage = "कृपया कार्यालय अभिलेख वर्गीकरण (मागील महिना अखेर) संख्या आवश्यक आहे")]
        [DisplayName("मागील महिना अखेर")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Last_Month_Classification_Achieved { get; set; }




        [Required(ErrorMessage = "कृपया कार्यालय अभिलेख वर्गीकरण (चालू महिना अखेर) संख्या आवश्यक आहे")]
        [DisplayName("चालू महिना अखेर")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Current_Month_Classification_Achieved { get; set; }



        [Required(ErrorMessage = "कृपया कार्यालय अभिलेख वर्गीकरण (एकुण) संख्या आवश्यक आहे")]
        [DisplayName("एकुण")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Total_Classification_Achieved { get; set; }



        [Required(ErrorMessage = "कृपया चालु महिना अखेर उद्दीष्टांच्या साध्यतेनुसार टक्केवारी आवश्यक आहे")]
        [DisplayName("चालु महिना अखेर उद्दीष्टांच्या साध्यतेनुसार टक्केवारी")]
        public Nullable<double> Current_Month_Percentage { get; set; }



        [Required(ErrorMessage = "कृपया मुल्यांकनानुसार प्राप्त गुण आवश्यक आहे")]
        [DisplayName("मुल्यांकनानुसार एकुण प्राप्त गुण")]
        public Nullable<double> Appraisal_Marks { get; set; }



        [Required(ErrorMessage = "कृपया  प्राप्त गुणांची टक्केवारी आवश्यक आहे")]
        [DisplayName("प्राप्त गुणांची टक्केवारी")]
        public Nullable<double> Appraisal_Percentage { get; set; }



        public bool NotApplicable { get; set; }

        public Nullable<int> Month { get; set; }

        public Nullable<int> Year { get; set; }


        [DisplayName("शेरा")]
        public string Remarks { get; set; } 

		public System.DateTime CreatedTime { get; set; }

        public virtual User User { get; set; }
    }
}
