//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Report30
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }

        [Required(ErrorMessage = "कृपया निधी आवश्यक आहे")]
        [DisplayName("बीडीस वर उपलब्ध करून देण्यात आलेला निधी (उद्दिष्ट)")]
        public Nullable<double> BDS_Funds_Aim { get; set; }

        [Required(ErrorMessage = "कृपया खर्च आवश्यक आहे")]
        [DisplayName("मागील महिन्यात झालेला खर्च")]
        
        public Nullable<double> Last_Month_Achieved_Expenses { get; set; }

        [Required(ErrorMessage = "कृपया खर्च आवश्यक आहे")]
        [DisplayName("चालु महिन्यात झालेला खर्च")]
        
        public Nullable<double> Current_Month_Achieved_Expenses { get; set; }

        [Required(ErrorMessage = "कृपया खर्च आवश्यक आहे")]
        [DisplayName("एकुण झालेला खर्च")]
        
        public Nullable<double> Total_Expenses { get; set; }


        [Required(ErrorMessage = "कृपया शिल्लक निधी आवश्यक आहे")]
        [DisplayName("शिल्लक निधी")]
        
        public Nullable<double> Balance_Amount { get; set; }

        [Required(ErrorMessage = "कृपया मुल्यांकनानुसार प्राप्त गुण आवश्यक आहे")]
        [DisplayName("मुल्यांकनानुसार एकुण प्राप्त गुण")]
        public Nullable<double> Appraisal_Marks { get; set; }


        [Required(ErrorMessage = "कृपया  प्राप्त गुणांची टक्केवारी आवश्यक आहे")]
        [DisplayName("प्राप्त गुणांची टक्केवारी")]
        public Nullable<double> Appraisal_Percentage { get; set; }

        public bool NotApplicable { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Remarks { get; set; } 

		public System.DateTime CreatedTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
