//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Report56
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }



        [Required(ErrorMessage = "कृपया उद्दीष्टाप्रमाणे संस्था बळकटीकरण संख्या आवश्यक आहे")]
        [DisplayName("चालु आर्थिक वर्षासाठी निश्चित केलेला लक्षांक")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Annual_Target { get; set; }


        [Required(ErrorMessage = "कृपया उद्दीष्टाप्रमाणे चालु महिना अखेर उद्दीष्ट संख्या आवश्यक आहे")]
        [DisplayName("चालु महिना अखेर उद्दीष्ट संख्या ")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Current_Month_Aim_Count { get; set; }



        [Required(ErrorMessage = "कृपया उद्दीष्टाप्रमाणे चालु महिना अखेर उद्दीष्ट रक्कम आवश्यक आहे")]
        [DisplayName("चालु महिना अखेर उद्दीष्ट रक्कम")]
        public Nullable<double> Current_Month_Aim_Amount { get; set; }


        [Required(ErrorMessage = "कृपया साध्यतेप्रमाणे मागील महिना अखेर साध्य संख्या आवश्यक आहे")]
        [DisplayName("मागील महिना अखेर साध्य संख्या")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Last_Month_Achieved_Count { get; set; }


        [Required(ErrorMessage = "कृपया साध्यतेप्रमाणे मागील महिना अखेर कार्यालय साध्य रक्कम आवश्यक आहे")]
        [DisplayName("मागील महिना अखेर कार्यालय साध्य रक्कम")]
        public Nullable<double> Last_Month_Achieved_Amount { get; set; }



        [Required(ErrorMessage = "कृपया साध्यतेप्रमाणे चालू महिना अखेर साध्य संख्या आवश्यक आहे")]
        [DisplayName("चालू महिना अखेर साध्य संख्या")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Current_Month_Achieved_Count { get; set; }



        [Required(ErrorMessage = "कृपया साध्यतेप्रमाणे चालू महिना अखेर साध्य रक्कम आवश्यक आहे")]
        [DisplayName("चालू महिना अखेर साध्य रक्कम")]
        public Nullable<double> Current_Month_Achieved_Amount { get; set; }



        [Required(ErrorMessage = "कृपया साध्यतेप्रमाणे एकुण संख्या आवश्यक आहे")]
        [DisplayName("एकुण संख्या")]
        [RegularExpression("([0-9][0-9]*[.]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Total_Count { get; set; }



        [Required(ErrorMessage = "कृपया साध्यतेप्रमाणे एकुण रक्कम आवश्यक आहे")]
        [DisplayName("एकुण रक्कम")]
        public Nullable<double> Total_Amount { get; set; }



        [Required(ErrorMessage = "कृपया टक्केवारी आवश्यक आहे")]
        [DisplayName("चालु महिना अखेर उद्दीष्टांच्या साध्यतेनुसार टक्केवारी")]
        public Nullable<double> Current_Month_Percentage { get; set; }



        [Required(ErrorMessage = "कृपया मुल्यांकनानुसार प्राप्त गुण आवश्यक आहे")]
        [DisplayName("मुल्यांकनानुसार एकुण प्राप्त गुण")]
        public Nullable<double> Appraisal_Marks { get; set; }



        [Required(ErrorMessage = "कृपया  प्राप्त गुणांची टक्केवारी आवश्यक आहे")]
        [DisplayName("प्राप्त गुणांची टक्केवारी")]
        public Nullable<double> Appraisal_Percentage { get; set; }


        public bool NotApplicable { get; set; }

        public Nullable<int> Month { get; set; }

        public Nullable<int> Year { get; set; }


        [DisplayName("शेरा")]
        public string Remarks { get; set; } 

		public System.DateTime CreatedTime { get; set; }

        public virtual User User { get; set; }
    }
}
