//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report11
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }
        public Nullable<int> Inquiry_C { get; set; }
        public Nullable<int> Inquiry_D { get; set; }
        public Nullable<int> Inquiry_Total { get; set; }
        public Nullable<int> Inquiry_Target_C { get; set; }
        public Nullable<int> Inquiry_Target_D { get; set; }
        public Nullable<int> Inquiry_Total_Target { get; set; }
        public Nullable<int> Inquiry_Achieved_C { get; set; }
        public Nullable<int> Inquiry_Achieved_D { get; set; }
        public Nullable<int> Inquiry_Total_Achieved { get; set; }
        public Nullable<int> Inquiry_Remaining_C { get; set; }
        public Nullable<int> Inquiry_Remaining_D { get; set; }
        public Nullable<int> Inquiry_Total_Remaining { get; set; }
        public Nullable<double> Appraisal_Marks { get; set; }
        public Nullable<double> Appraisal_Percentage { get; set; }
        public bool NotApplicable { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Remarks { get; set; }
    
        public virtual User User { get; set; }
    }
}
