//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportA
    {
        public int RaId { get; set; }
        public Nullable<int> ReportBId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> Goal { get; set; }
        public Nullable<int> Completed { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> Percentage { get; set; }
    
        public virtual ReportB ReportB { get; set; }
    }
}
