//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Report31
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }

        public Nullable<int> Aim { get; set; }

        [Required(ErrorMessage = "कृपया अहवाल जमा केल्याची तारीख आवश्यक आहे")]
        [DisplayName("मागील महिन्यात अहवाल जमा केल्याची तारीख")]
        [Range(1, 31, ErrorMessage = "कृपया 1-31 मध्ये योग्य तारीख नमुद करा")]
        public Nullable<int> Last_Month_Report_Submitted { get; set; }

        [Required(ErrorMessage = "कृपया अहवाल जमा केल्याची तारीख आवश्यक आहे")]
        [DisplayName("चालु महिन्यात अहवाल जमा केल्याची तारीख")]
        [Range(1, 31, ErrorMessage = "कृपया 1-31 मध्ये  योग्य तारीख नमुद करा")]
        public Nullable<int> Current_Month_Report_Submitted { get; set; }



        [Required(ErrorMessage = "कृपया मुल्यांकनानुसार प्राप्त गुण आवश्यक आहे")]
        [DisplayName("मुल्यांकनानुसार एकुण प्राप्त गुण")]
        public Nullable<double> Appraisal_Marks { get; set; }

        public bool NotApplicable { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Remarks { get; set; } 

		public System.DateTime CreatedTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
