//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report52
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }
        public Nullable<int> Last_Month_Pending_Cases { get; set; }
        public Nullable<int> Current_Month_Received_Cases { get; set; }
        public Nullable<int> Total_Cases { get; set; }
        public Nullable<int> Last_Month_Cases_Aim { get; set; }
        public Nullable<int> Current_Month_Cases_Aim { get; set; }
        public Nullable<int> Total_Cases_Aim { get; set; }
        public Nullable<int> Last_Month_Achieved { get; set; }
        public Nullable<int> Current_Month_Achieved { get; set; }
        public Nullable<int> Total_Achieved { get; set; }
        public Nullable<double> Appraisal_Marks { get; set; }
        public Nullable<double> Appraisal_Percentage { get; set; }
        public bool NotApplicable { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string Remarks { get; set; }
    
        public virtual User User { get; set; }
    }
}
