//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportB()
        {
            this.ReportAs = new HashSet<ReportA>();
        }
    
        public int RbId { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> Goal { get; set; }
        public Nullable<int> Completed { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> Percentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportA> ReportAs { get; set; }
        public virtual UsersReport UsersReport { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
