//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Report64
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }


        [Required(ErrorMessage = "कृपया अपिलांची संख्या आवश्यक आहे")]
        [DisplayName("एकूण प्राप्त अपिलांची संख्या")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Total_Appeal { get; set; }



        [Required(ErrorMessage = "कृपया निकाली काढलेल्या अपिलांची संख्या आवश्यक आहे")]
        [DisplayName("एकूण प्राप्त अपिलांपैकी चार महिन्याच्या आत निकाली काढलेल्या अपिलांची संख्या")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Resolved_Appeal { get; set; }


        [Required(ErrorMessage = "कृपया मुल्यांकनानुसार प्राप्त गुण आवश्यक आहे")]
        [DisplayName("मुल्यांकनानुसार एकुण प्राप्त गुण")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<double> Appraisal_Marks { get; set; }



        [Required(ErrorMessage = "कृपया प्राप्त गुणांची टक्केवारी आवश्यक आहे")]
        [DisplayName("अपिल निकाली काढलेल्याची टक्केवारी")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<double> Resolved_Percentage { get; set; }


        public bool NotApplicable { get; set; }


        public Nullable<int> Month { get; set; }


        public Nullable<int> Year { get; set; }


        [DisplayName("शेरा")]
        public string Remarks { get; set; }

        public virtual User User { get; set; }
    }
}
