//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance_Appraisal_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Report12
    {
        public int RId { get; set; }
        public Nullable<int> UId { get; set; }



        [Required(ErrorMessage = "कृपया कार्यरत अधिकारी / कर्मचारी संख्या आवश्यक आहे")]
        [DisplayName("कार्यरत अधिकारी / कर्मचारी संख्या")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Officer_Count { get; set; }



        [Required(ErrorMessage = "कृपया सेवानिवृत्त झालेल्या अधिकारी / कर्मचाऱ्यांची संख्या आवश्यक आहे")]
        [DisplayName("सेवानिवृत्त झालेल्या अधिकारी / कर्मचाऱ्यांची संख्या")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Retired_Officer_Count { get; set; }



        [Required(ErrorMessage = "कृपया सेवानिवृत्ती विषय लाभ अदा केलेल्या अधिकारी / कर्मचारी (उद्दिष्ट) संख्या आवश्यक आहे")]
        [DisplayName("उद्दिष्ट")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Retirement_Benefits_Target { get; set; }




        [Required(ErrorMessage = "कृपया सेवानिवृत्ती विषय लाभ अदा केलेल्या अधिकारी / कर्मचारी (पूर्ण) संख्या आवश्यक आहे")]
        [DisplayName("पूर्ण")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Retirement_Benefits_Achieved { get; set; }



        [Required(ErrorMessage = "कृपया सेवानिवृत्ती विषय लाभ अदा केलेल्या अधिकारी / कर्मचारी (शिल्लक) संख्या आवश्यक आहे")]
        [DisplayName("शिल्लक")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<int> Retirement_Benefits_Pendig { get; set; }


        [Required(ErrorMessage = "कृपया मुल्यांकनानुसार प्राप्त गुण आवश्यक आहे")]
        [DisplayName("मुल्यांकनानुसार एकुण प्राप्त गुण")]
        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "फक्त संख्या प्रविष्ट करा")]
        public Nullable<double> Appraisal_Marks { get; set; }


        [Required(ErrorMessage = "कृपया  प्राप्त गुणांची टक्केवारी आवश्यक आहे")]
        [DisplayName("प्राप्त गुणांची टक्केवारी")]
        public Nullable<double> Appraisal_Percentage { get; set; }



        public bool NotApplicable { get; set; }

        public Nullable<int> Month { get; set; }

        public Nullable<int> Year { get; set; }



        [DisplayName("शेरा")]
        public string Remarks { get; set; }

        public virtual User User { get; set; }
    }
}
